const products = [
  {name:'Northern Lights Expedition', destination:'Tromsø, Norway', type:'Adventure', icon:'✦', colour:'#557b98', status:'Processing', score:'88%'},
  {name:'Amalfi Coast Escape', destination:'Campania, Italy', type:'Luxury', icon:'☀', colour:'#d47c5b', status:'Published', score:'96%'},
  {name:'Kyoto & Osaka Discovery', destination:'Japan', type:'Culture', icon:'⛩', colour:'#ba695a', status:'Published', score:'93%'},
  {name:'Safari Under Canvas', destination:'Maasai Mara, Kenya', type:'Wildlife', icon:'🦁', colour:'#b48349', status:'Published', score:'91%'},
  {name:'Island Hopping Escape', destination:'Cyclades, Greece', type:'Beach', icon:'⛵', colour:'#4485a2', status:'Draft', score:'82%'},
  {name:'Patagonian Trail', destination:'Chile & Argentina', type:'Adventure', icon:'⛰', colour:'#527b72', status:'Published', score:'95%'}
];
let total = 24, generated = 186, hours = 47.5;
const $ = s => document.querySelector(s);
const activity = [
  ['✦','violet','Content generated','Amalfi Coast Escape · 3 minutes ago'],
  ['⌕','amber','SEO score improved','Kyoto & Osaka Discovery is now at 93% · 18 min ago'],
  ['◈','mint','Product classified','Safari Under Canvas · 42 min ago'],
  ['↥','coral','New supplier data received','3 records from Atlas Travel · 1 hr ago']
];
function renderActivity(){ $('#activityList').innerHTML=activity.map(a=>`<div class="activity"><div class="activity-icon ${a[1]}">${a[0]}</div><div><strong>${a[2]}</strong><p>${a[3]}</p></div><time>Today</time></div>`).join('') }
function renderRecent(){ $('#recentProducts').innerHTML=products.slice(0,3).map(p=>`<div class="product-row"><div class="product-visual" style="background:${p.colour}">${p.icon}</div><div><strong>${p.name}</strong><small>${p.destination} · ${p.type}</small></div><span class="row-status">${p.status}</span></div>`).join('') }
function renderProducts(list=products){ $('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-card-top" style="background:linear-gradient(135deg,${p.colour},#18333d)"><span class="destination-art">${p.icon}</span><span class="category-tag">${p.type.toUpperCase()}</span></div><div class="product-card-body"><h3>${p.name}</h3><p>${p.destination}</p><div class="card-footer"><span>SEO health ${p.score}</span><span class="row-status">${p.status}</span></div></div></article>`).join('') }
function renderTop(){ $('#topProducts').innerHTML=products.slice(1,5).map((p,i)=>`<div class="top-row"><div class="top-name"><span class="rank">0${i+1}</span><span class="product-visual" style="background:${p.colour};width:28px;height:28px">${p.icon}</span>${p.name}</div><span>${['12.4k','9.8k','8.7k','6.1k'][i]} impressions</span><span class="positive">↑ ${[42,28,23,19][i]}%</span><span>${p.score} SEO</span></div>`).join('') }
function renderNumbers(){ $('#totalProducts').firstChild.data=total; $('#contentCount').firstChild.data=generated; $('#hoursSaved').firstChild.data=hours; $('#navProductCount').textContent=total }
function toast(message){ const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200) }
function switchView(name){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const labels={dashboard:['Good morning, Alex ✦','Here’s what your automation engine has been working on.'],products:['Product library','Manage the travel experiences your AI can bring to life.'],automation:['Automation studio','Configure the path from supplier information to customer-ready content.'],insights:['Performance insights','Track the business impact of intelligent content automation.']};$('#pageTitle').textContent=labels[name][0];$('#pageSubtitle').textContent=labels[name][1];window.scrollTo({top:0,behavior:'smooth'}) }
function processProduct(raw, productName){ const text=raw.toLowerCase(); const name=productName || (text.includes('kyoto')?'Kyoto & Osaka Discovery':(text.includes('maasai')||text.includes('kenya'))?'Safari Under Canvas':'Northern Lights Expedition'); const destination=text.includes('kyoto')?'Japan':(text.includes('maasai')||text.includes('kenya'))?'Maasai Mara, Kenya':'Tromsø, Norway'; $('#outputStatus').textContent='PROCESSING';$('#outputStatus').className='status-pill processing';$('#outputState').textContent='Classifying product and drafting content…';$('#aiOutput').innerHTML='<div class="empty-output"><div class="empty-star">✦</div><p>AI is analysing inclusions, audience signals and seasonal intent…</p></div>'; setTimeout(()=>{const output=`<div class="output-grid"><div class="output-item"><span>CLASSIFICATION</span><strong>Adventure · Premium · Winter</strong></div><div class="output-item"><span>IDEAL TRAVELLER</span><strong>Couples & experience seekers</strong></div><div class="output-item wide"><span>GENERATED STORY</span><p>Chase the aurora above Norway’s Arctic coast on an intimate escape designed for travellers who want the extraordinary.</p></div><div class="output-item"><span>SEO TITLE</span><strong>${name} | Travelitude</strong></div><div class="output-item"><span>USE-CASE TAGS</span><div class="tag-list"><i>Romantic escape</i><i>Bucket list</i><i>Winter sun</i></div></div></div>`;$('#aiOutput').innerHTML=output;$('#outputStatus').textContent='COMPLETE';$('#outputStatus').className='status-pill';$('#outputState').textContent='Content, SEO and travel use-cases ready';generated+=3;hours+=1.5;renderNumbers();activity.unshift(['✦','violet','AI workflow completed',`${name} is ready to review · just now`]);renderActivity();toast('AI output is ready for review');},1300) }
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));
$('#processButton').addEventListener('click',()=>{const raw=$('#productInput').value.trim();if(!raw)return toast('Add product information first');processProduct(raw)});$('#loadSampleButton').addEventListener('click',()=>{$('#productInput').value='10-night Kyoto & Osaka discovery. Ryokan stay, tea ceremony, culinary tour and private guides. Designed for culture-loving couples.';toast('Kyoto demo product loaded')});
$('#runAllButton').addEventListener('click',()=>{toast('Automation queue started — 3 products in progress');setTimeout(()=>{generated+=9;hours+=4.5;renderNumbers();$('.automation-note').innerHTML='<span>✓</span><span><strong>Today’s automation run complete</strong> — all 3 products are ready for review.</span><span class="live-dot">DONE</span>';activity.unshift(['✓','mint','Automation run completed','3 products enriched and optimised · just now']);renderActivity()},1500)});
$('#exploreButton').addEventListener('click',()=>{switchView('automation');$('#productInput').value='7-night family adventure in Costa Rica: rainforest lodge, wildlife walks, zip-lining, beach stay and private transfers. Suitable for families with children aged 7+.';toast('Family-travel opportunity loaded into the studio')});
$('#importButton').addEventListener('click',()=>{switchView('automation');toast('Supplier import area is ready')});$('#newProductButton').addEventListener('click',()=>$('#modal').classList.add('open'));$('#modalClose').addEventListener('click',()=>$('#modal').classList.remove('open'));$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')});$('#modalProcess').addEventListener('click',()=>{const name=$('#newProductName').value.trim(),brief=$('#newProductBrief').value.trim();if(!name||!brief)return toast('Add a product name and brief');products.unshift({name,destination:'New destination',type:'New',icon:'✦',colour:'#7563d6',status:'Processing',score:'—'});total++;renderProducts();renderRecent();renderNumbers();$('#modal').classList.remove('open');switchView('automation');$('#productInput').value=brief;processProduct(brief,name)});
$('#productSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderProducts(products.filter(p=>(p.name+p.destination+p.type).toLowerCase().includes(q)))});$('#downloadReport').addEventListener('click',()=>toast('Performance report prepared for download (demo)'));
renderActivity();renderRecent();renderProducts();renderTop();renderNumbers();
